/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Services.Services;
import Type.bao;
import Type.sach;
import Type.tapChi;

/**
 *
 * @author ADMIN
 */
public class AddItem extends javax.swing.JFrame {

    Services services;
    sach sach;
    tapChi tapChi;
    bao bao;
    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents();
        services = new Services();
        sach = new sach();
        tapChi = new tapChi();
        bao = new bao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        sachPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nxbTextField1 = new javax.swing.JTextField();
        soBanPhatHanhTextField1 = new javax.swing.JTextField();
        tenTGTextfield1 = new javax.swing.JTextField();
        soTrangTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sachRadioBtn = new javax.swing.JRadioButton();
        tapChiRadioBtn = new javax.swing.JRadioButton();
        baoRadioBtn = new javax.swing.JRadioButton();
        BackButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelThu3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelThu4 = new javax.swing.JLabel();
        tenNXBTextField = new javax.swing.JTextField();
        soBanPHTextField = new javax.swing.JTextField();
        textFieldThu3 = new javax.swing.JTextField();
        textFieldThu4 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tên NXB:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Số bản phát hành:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tên Tác Gỉa:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Số Trang:");

        javax.swing.GroupLayout sachPanel1Layout = new javax.swing.GroupLayout(sachPanel1);
        sachPanel1.setLayout(sachPanel1Layout);
        sachPanel1Layout.setHorizontalGroup(
            sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sachPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sachPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sachPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tenTGTextfield1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(soBanPhatHanhTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nxbTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soTrangTextField1))
                .addGap(25, 25, 25))
        );
        sachPanel1Layout.setVerticalGroup(
            sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sachPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nxbTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soBanPhatHanhTextField1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenTGTextfield1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sachPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soTrangTextField1)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Tài Liệu");

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 20, 20));

        buttonGroup1.add(sachRadioBtn);
        sachRadioBtn.setSelected(true);
        sachRadioBtn.setText("Sách");
        sachRadioBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sachRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sachRadioBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sachRadioBtn);

        buttonGroup1.add(tapChiRadioBtn);
        tapChiRadioBtn.setText("Tạp Chí");
        tapChiRadioBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tapChiRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tapChiRadioBtnActionPerformed(evt);
            }
        });
        jPanel1.add(tapChiRadioBtn);

        buttonGroup1.add(baoRadioBtn);
        baoRadioBtn.setText("Báo");
        baoRadioBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baoRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baoRadioBtnActionPerformed(evt);
            }
        });
        jPanel1.add(baoRadioBtn);

        BackButton.setText("Quay lại");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        addButton.setText("Thêm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tên NXB:");

        jLabelThu3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelThu3.setText("Tên Tác Gỉa:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Số Bản Phát Hành:");

        jLabelThu4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelThu4.setText("Số Trang:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelThu3)
                                            .addComponent(jLabelThu4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tenNXBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(soBanPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textFieldThu3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textFieldThu4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenNXBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soBanPHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThu3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldThu3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThu4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldThu4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(addButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sachRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sachRadioBtnActionPerformed
        // TODO add your handling code here:
        jLabelThu3.setText("Tên Tác Gỉa:");
        jLabelThu4.setText("Số Trang:");
        textFieldThu3.setText("");
        textFieldThu4.setEnabled(true);

    }//GEN-LAST:event_sachRadioBtnActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here
        if (sachRadioBtn.isSelected()){
            sach.setTenNXB(tenNXBTextField.getText());
            sach.setSoBanPhatHanh(Integer.parseInt(soBanPHTextField.getText()));
            sach.setTenTacGia(textFieldThu3.getText());
            sach.setSoTrang(Integer.parseInt(textFieldThu4.getText()));
            
            services.addSach(sach);
            new LibraryView("SA000").setVisible(true);
            this.dispose();
        }
        if (tapChiRadioBtn.isSelected()){
            tapChi.setTenNXB(tenNXBTextField.getText());
            tapChi.setSoBanPhatHanh(Integer.parseInt(soBanPHTextField.getText()));
            tapChi.setSoPhatHanh(Integer.parseInt(textFieldThu3.getText()));
            tapChi.setThangPhatHanh(textFieldThu4.getText());
            
            services.addTapChi(tapChi);
            new LibraryView("TC000").setVisible(true);
            this.dispose();
        }
        if (baoRadioBtn.isSelected()){
            bao.setTenNXB(tenNXBTextField.getText());
            bao.setSoBanPhatHanh(Integer.parseInt(soBanPHTextField.getText()));
            bao.setNgayPhatHanh(textFieldThu3.getText());
            
            services.addBao(bao);
            new LibraryView("BA000").setVisible(true);
            this.dispose();
        }
        
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        new LibraryView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void tapChiRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tapChiRadioBtnActionPerformed
        // TODO add your handling code here:
        jLabelThu3.setText("Số Phát Hành:");
        jLabelThu4.setText("Tháng Phát Hành:");
        textFieldThu3.setText("");
        textFieldThu4.setEnabled(true);
    }//GEN-LAST:event_tapChiRadioBtnActionPerformed

    private void baoRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baoRadioBtnActionPerformed
        // TODO add your handling code here:
        jLabelThu3.setText("Ngày Phát Hành:");
        jLabelThu4.setText("--------");
        textFieldThu3.setText("yyyy/mm/dd");
        textFieldThu4.setEnabled(false);
    }//GEN-LAST:event_baoRadioBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton addButton;
    private javax.swing.JRadioButton baoRadioBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelThu3;
    private javax.swing.JLabel jLabelThu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nxbTextField1;
    private javax.swing.JPanel sachPanel1;
    private javax.swing.JRadioButton sachRadioBtn;
    private javax.swing.JTextField soBanPHTextField;
    private javax.swing.JTextField soBanPhatHanhTextField1;
    private javax.swing.JTextField soTrangTextField1;
    private javax.swing.JRadioButton tapChiRadioBtn;
    private javax.swing.JTextField tenNXBTextField;
    private javax.swing.JTextField tenTGTextfield1;
    private javax.swing.JTextField textFieldThu3;
    private javax.swing.JTextField textFieldThu4;
    // End of variables declaration//GEN-END:variables
}
