/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Services.Services;
import Type.bao;
import Type.sach;
import Type.tapChi;
/**
 *
 * @author ADMIN
 */
public class LibraryView extends javax.swing.JFrame {

    private Services Services;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form LibraryView
     */
    public LibraryView() {
        initComponents();
        DataSach();
    }
    
    public void DataSach(){
        Services = new Services();
        defaultTableModel = new DefaultTableModel();
        
        tableOfContents.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã Tài Liệu");
        defaultTableModel.addColumn("Tên NXB");
        defaultTableModel.addColumn("Số Bản Phát Hành");
        defaultTableModel.addColumn("Tên Tác Gỉa");
        defaultTableModel.addColumn("Số Trang");
        
        List<sach> Sach = Services.getAllSach();
        
        for (sach i:Sach)
        {
            defaultTableModel.addRow(new Object[]{i.getMaTaiLieu(),i.getTenNXB(),i.getSoBanPhatHanh(),
                i.getTenTacGia(),i.getSoTrang()});
        }
    }
    
    public void DataTapChi(){
        Services = new Services();
        defaultTableModel = new DefaultTableModel();
        
        tableOfContents.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã Tài Liệu");
        defaultTableModel.addColumn("Tên NXB");
        defaultTableModel.addColumn("Số Bản Phát Hành");
        defaultTableModel.addColumn("Số Phát Hành");
        defaultTableModel.addColumn("Tháng Phát Hành");
        
        List<tapChi> TapChi = Services.getAllTapChi();
        
        for (tapChi i:TapChi)
        {
            defaultTableModel.addRow(new Object[]{i.getMaTaiLieu(),i.getTenNXB(),i.getSoBanPhatHanh()
            ,i.getSoPhatHanh(),i.getThangPhatHanh()});
        }
    }
    
    public void DataBao(){
        Services = new Services();
        defaultTableModel = new DefaultTableModel();
        
        tableOfContents.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã Tài Liệu");
        defaultTableModel.addColumn("Tên NXB");
        defaultTableModel.addColumn("Số Bản Phát Hành");
        defaultTableModel.addColumn("Ngày Phát Hành");
        
        List<bao> Bao = Services.getAllBao();
        
        for (bao i:Bao)
        {
            defaultTableModel.addRow(new Object[]{i.getMaTaiLieu(), i.getTenNXB(), i.getSoBanPhatHanh()
            ,i.getNgayPhatHanh()});
        }
    }
    
    public LibraryView(String x){
        initComponents();
        if(x.length()>4)
        {
            if (x.substring(0,2).equals("SA")) 
            {
                DataSach();
            }
            if (x.substring(0,2).equals("TC"))
            {
                DataTapChi();
            }
            if (x.substring(0,2).equals("BA"))
            {
               DataBao();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sachButton = new javax.swing.JButton();
        tapChiButton = new javax.swing.JButton();
        baoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfContents = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Thư Viện");

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 20, 20));

        sachButton.setBackground(new java.awt.Color(255, 204, 255));
        sachButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sachButton.setText("Sách");
        sachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sachButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sachButton);

        tapChiButton.setBackground(new java.awt.Color(255, 204, 255));
        tapChiButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tapChiButton.setText("Tạp Chí");
        tapChiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tapChiButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tapChiButton);

        baoButton.setBackground(new java.awt.Color(255, 204, 255));
        baoButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        baoButton.setText("Báo");
        baoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(baoButton);

        tableOfContents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOfContents.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableOfContents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableOfContents);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        addButton.setBackground(new java.awt.Color(153, 255, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addButton.setText("Thêm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addButton);

        editButton.setBackground(new java.awt.Color(255, 204, 51));
        editButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editButton.setText("Sửa");
        jPanel3.add(editButton);

        deleteButton.setBackground(new java.awt.Color(255, 153, 153));
        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel3.add(deleteButton);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Thoát");
        jPanel3.add(jButton2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tìm Kiếm Theo NXB:");

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(153, 255, 153));
        searchButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchButton.setText("Tìm Kiếm");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sachButtonActionPerformed
        // TODO add your handling code here:
        DataSach();
    }//GEN-LAST:event_sachButtonActionPerformed

    private void tapChiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tapChiButtonActionPerformed
        // TODO add your handling code here:
       DataTapChi();
    }//GEN-LAST:event_tapChiButtonActionPerformed

    private void baoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baoButtonActionPerformed
        // TODO add your handling code here:
       DataBao();
    }//GEN-LAST:event_baoButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        new AddItem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = tableOfContents.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(LibraryView.this, "Chưa chọn Tài Liệu", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(LibraryView.this, "Chắc chắn xóa tài liệu này?");
            String maTaiLieu = String.valueOf(tableOfContents.getValueAt(row, 0));
            if (confirm == JOptionPane.YES_OPTION && maTaiLieu.substring(0, 2).equals("SA")){
                Services.deleteSach(maTaiLieu);
                defaultTableModel.setRowCount(0);
                DataSach();
            }
            if (confirm == JOptionPane.YES_OPTION && maTaiLieu.substring(0, 2).equals("TC")){
                Services.deleteTapChi(maTaiLieu);
                defaultTableModel.setRowCount(0);
                DataTapChi();
            }
            if (confirm == JOptionPane.YES_OPTION && maTaiLieu.substring(0, 2).equals("BA")){
                Services.deleteBao(maTaiLieu);
                defaultTableModel.setRowCount(0);
                DataBao();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String tenNXB = "";
        tenNXB = searchTextField.getText();
        if(sachButton.isSelected()){
            Services = new Services();
            defaultTableModel = new DefaultTableModel();

            tableOfContents.setModel(defaultTableModel);
            defaultTableModel.setRowCount(0);
            defaultTableModel.addColumn("Mã Tài Liệu");
            defaultTableModel.addColumn("Tên NXB");
            defaultTableModel.addColumn("Số Bản Phát Hành");
            defaultTableModel.addColumn("Tên Tác Gỉa");
            defaultTableModel.addColumn("Số Trang");

            List<sach> Sach = Services.searchSach(tenNXB);  

            for (sach i:Sach)
            {
                defaultTableModel.addRow(new Object[]{i.getMaTaiLieu(),i.getTenNXB(),i.getSoBanPhatHanh(),
                    i.getTenTacGia(),i.getSoTrang()});
            }    
        }
        if(tapChiButton.isSelected()){
            Services = new Services();
            defaultTableModel = new DefaultTableModel();

            tableOfContents.setModel(defaultTableModel);

            defaultTableModel.addColumn("Mã Tài Liệu");
            defaultTableModel.addColumn("Tên NXB");
            defaultTableModel.addColumn("Số Bản Phát Hành");
            defaultTableModel.addColumn("Số Phát Hành");
            defaultTableModel.addColumn("Tháng Phát Hành");

            List<tapChi> TapChi = Services.searchTapChi(tenNXB);

            for (tapChi i:TapChi)
            {
                defaultTableModel.addRow(new Object[]{i.getMaTaiLieu(),i.getTenNXB(),i.getSoBanPhatHanh()
                ,i.getSoPhatHanh(),i.getThangPhatHanh()});
            }    
        }
        if(baoButton.isSelected()){
            Services = new Services();
            defaultTableModel = new DefaultTableModel();

            tableOfContents.setModel(defaultTableModel);

            defaultTableModel.addColumn("Mã Tài Liệu");
            defaultTableModel.addColumn("Tên NXB");
            defaultTableModel.addColumn("Số Bản Phát Hành");
            defaultTableModel.addColumn("Ngày Phát Hành");

            List<bao> Bao = Services.searchBao(tenNXB);

            for (bao i:Bao)
            {
                defaultTableModel.addRow(new Object[]{i.getMaTaiLieu(), i.getTenNXB(), i.getSoBanPhatHanh()
                ,i.getNgayPhatHanh()});
            }    
        }
       
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton baoButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sachButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable tableOfContents;
    private javax.swing.JButton tapChiButton;
    // End of variables declaration//GEN-END:variables

    
}
